# Generated by Django 4.2.2 on 2023-11-16 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airveda', '0002_rename_temperature_temperaturereading_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='humidityreading',
            old_name='humidity',
            new_name='value',
        ),
    ]
